---
- hosts: all
  become: yes

  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - make
        - vim
        - curl
        - git
        - unzip
        - apt-transport-https