---
- hosts: all
  become: yes

  tasks:
    - shell: echo "Validation"

    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip
        - fish
        - falkon
        - rofi
        - docker
          
    - name: Add alacritty ppa
      ansible.builtin.apt_repository:
        repo: ppa:aslatter/ppa

    - name: Install alacritty
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - alacritty

    - name: Backpup openbox files
      become: no
      copy: src=~/.config/openbox/lxqt-rc.yml dest=~/.config/openbox/lxqt-rc-bkp.yml

    - name: Download lxqt-rc.xml
      become: no
      get_url:
        url: https://gist.githubusercontent.com/sergsoares/89f085f6a6b34a40741dbf2aae54932b/raw/11e73608f02613483bd02a77675f5b414c77570e/lxqt-rc.xml
        dest: ~/.config/openbox/lxqt-rc.yml
        mode: '0440'
