---
- hosts: all
  become: yes

  tasks:
    - name: Creates directory
      file:
        path: /opt/dbeaver-ce_22.0.1_amd64 #TODO: use variable
        state: directory
    
    - name: Download Dbeaver binary
      get_url:
        url: "https://download.dbeaver.com/community/22.0.1/dbeaver-ce_22.0.1_amd64.deb" #TODO: use variable
        dest: "/opt/dbeaver-ce_22.0.1_amd64/dbeaver-ce_22.0.1_amd64.deb" #TODO: use variable

    - name: Install Dbeaver
      apt:
        deb: /opt/dbeaver-ce_22.0.1_amd64/dbeaver-ce_22.0.1_amd64.deb