---
- hosts: all
  become: yes

  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add Sublime repository to list of repositories
      shell: |
        set -o pipefail
        echo "deb http://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
        creates=/etc/apt/sources.list.d/sublime-text.list
      args:
        executable: /bin/bash

    - name: Update apt cache
      apt: update_cache=yes
      become: true

    - name: Install Sublime
      apt:
        name: sublime-text
        state: present
      become: true